[package]
name = "geph4-protocol"
version = "0.3.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"
description="geph4 protocol helpers"
license="GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

acidjson= "0.1.0"
anyhow = "1.0.43"
async-net= "1.6.1" 
bincode = "1.3.3"
bytes={ version = "1.0.1", features = ["serde"] }
ed25519-dalek={ version = "1.0.1", features = ["serde"] }
event-listener= "2.5.1"
fastrand = "1.5.0"
futures-util= "0.3.17"
geph4-aioutils = "0.1.3"
geph4-binder-transport = "0.2"
hex = "0.4.3"
http-types = "2.12.0"
log = "0.4.14"
mizaru = "0.1.3"
once_cell= "1.8.0"
parking_lot = { version = "0.11.2", features = ["serde"] }
rand= "0.7.3"
regex= "1.5.4"
rsa-fdh = "0.5.0"
serde={ version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
sha2 = "0.9.8"
smol= "1.2.5"
smolscale= "0.3.16"
smol-timeout = "0.6.0"
#sosistab={path="../sosistab"}
strsim = "0.10.0"
tap= "1.0.1"

x25519-dalek={ version = "1.1.1", features = ["serde"] }
sosistab = "0.4.45"

# sosistab= "0.4.4"
