[package]
name = "geph4-protocol"
version = "0.1.2-alpha.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"
description="geph4 protocol helpers"
license="GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde={ version = "1.0.130", features = ["derive"] }
bytes={ version = "1.0.1", features = ["serde"] }
smol= "1.2.5"
# sosistab= "0.4.4"
